contact/urls.py
from django.conf.urls import url

from . import views

app_name = 'contact'
urlpatterns = [
    url(r'^$', views.contact, name='contact'),
]

reports/urls.py
from django.conf.urls import url

from . import views

app_name = 'reports'
urlpatterns = [
    url(r'^$', views.BrowseView.as_view(), name='reports'),
    url(r'^graphite/(.*)', views.graphite, name='graphite'),
    url(r'^actual/(.*)', views.actual, name='actual'),
    url(r'^about/$', views.about, name='about'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

reports_beta/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index

admin.site.site_header = 'ResPlat Reporting: Administration'
admin.site.site_title = 'ResPlat Reporting'

urlpatterns = [
    url('^$', index, name='index'),
    url(r'^uom_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^reports/', include('reports.urls')),
    url(r'^uom_admin/', admin.site.urls),
    url(r'^contact/', include('contact.urls')),
    url('^', include('django.contrib.auth.urls', namespace='auth')),
    url('^registration/', include('registration.urls')),
]

reports/models.py
import datetime

from django.db import models
from django.utils import timezone
from markdown import markdown


class Report(models.Model):
    report_title = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    d3_file_name = models.CharField(max_length=100, default='.js')
    description = models.TextField(blank=True, null=True)
    description_html = models.TextField(editable=False, default='')
    related = models.OneToOneField('Report', on_delete=models.DO_NOTHING,
                                   null=True, blank=True)

    def __str__(self):
        return self.report_title

    def was_published_recently(self):
        """
        A handy field to let us see the newly created reports in the
        Admin console.
        :return: True if was published in the last day, False otherwise
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def save(self, *args, **kwargs):
        self.description_html = markdown(self.description)
        super(Report, self).save(*args, *kwargs)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class CloudCapacity(models.Model):
    date = models.TextField(primary_key=True)
    nectar_contribution = models.IntegerField()
    uom_contribution = models.IntegerField()
    co_contribution = models.IntegerField()

    def __str__(self):
        return '%s: %s' % (self.__class__.__name__, self.date)

    class Meta:
        managed = False
        db_table = 'cloud_capacity'


class CloudProjectFaculty(models.Model):
    project_id = models.TextField(unique=True, max_length=32,
                                  null=False, primary_key=True,
                                  default="0",
                                  help_text="The projects ID")
    chief_investigator = models.CharField(max_length=75, blank=True, null=True,
                                          help_text="The nominated chief "
                                                    "investigator's email")
    contact_email = models.CharField(max_length=75, blank=True, null=True,
                                     help_text="The applicant's email")
    description = models.CharField(max_length=64, blank=True, null=True,
                                   help_text="The project description")
    for_code = models.CharField(max_length=6, blank=True, null=True,
                                help_text="The highest weighted FOR code")
    allocated_faculty = models.CharField(max_length=7, blank=True, null=True,
                                         help_text="The faculty we have "
                                                   "decided the project "
                                                   "belongs to")

    class Meta:
        db_table = 'cloud_project_faculty'


class CloudTotalsByFaculty(models.Model):
    # All field names lowercased.
    date = models.TextField(unique=True, blank=False, null=False,
                            primary_key=True,
                            help_text="The date on which the values "
                                      "in the row were calculated")
    foa = models.IntegerField(db_column='FoA', blank=False, null=False)
    vas = models.IntegerField(db_column='VAS', blank=False, null=False)
    fbe = models.IntegerField(db_column='FBE', blank=False, null=False)
    mse = models.IntegerField(db_column='MSE', blank=False, null=False)
    mgse = models.IntegerField(db_column='MGSE', blank=False, null=False)
    mdhs = models.IntegerField(db_column='MDHS', blank=False, null=False)
    fos = models.IntegerField(db_column='FoS', blank=False, null=False)
    abp = models.IntegerField(db_column='ABP', blank=False, null=False)
    mls = models.IntegerField(db_column='MLS', blank=False, null=False)
    vcamcm = models.IntegerField(db_column='VCAMCM', blank=False, null=False)
    services = models.IntegerField(db_column='Other', blank=False, null=False)
    unknown = models.IntegerField(db_column='Unknown', blank=False, null=False)

    def __str__(self):
        return '%s: %s' % (self.__class__.__name__, self.date)

    class Meta:
        abstract = True


class CloudAllocated(CloudTotalsByFaculty):
    """
    Contains the totals for the vcpu's allocated by each faculty
    """

    class Meta:
        db_table = 'cloud_allocated'


class CloudUsed(CloudTotalsByFaculty):
    """
    Contains the totals for the number of vcpu's fired up by each faculty
    """

    class Meta:
        db_table = 'cloud_used'


class CloudActiveUsers(models.Model):
    """
    Contains the active users.
    """
    date = models.TextField(primary_key=True, blank=False, null=False,
                            help_text="The date on which the values in "
                                      "the row were calculated")
    at_uom_only = models.IntegerField(blank=False, null=False,
                                      help_text="The number of UoM users who "
                                                "are only running VM's in UoM "
                                                "cells")
    elsewhere_only = models.IntegerField(blank=False, null=False,
                                         help_text="The number of UoM users "
                                                   "who are only running VM's "
                                                   "in cells outside of UoM")
    in_both = models.IntegerField(blank=False, null=False,
                                  help_text="The number of UoM users who are "
                                            "running VM's in both UoM cells "
                                            "and cells outside of UoM")
    others_at_uom = models.IntegerField(blank=False, null=False,
                                        help_text="Users not from UoM who are "
                                                  "running VM's in UoM cells")

    def __str__(self):
        return '%s: %s' % (self.__class__.__name__, self.date)

    class Meta:
        managed = False
        db_table = 'cloud_active_users'


class CloudTopTwenty(models.Model):
    """
    The top twenty UoM users of the cloud, by date.
    """
    date = models.TextField(primary_key=True,
                            help_text="The date on which the values "
                                      "were calculated")
    project_id = models.CharField(primary_key=True, max_length=32,
                                  help_text="The project ID")
    vcpus = models.IntegerField(help_text="The project VCPU count on the date")
    tenant_name = models.CharField(max_length=64,
                                   help_text="The project's formal name")

    def __str__(self):
        return '%s: %s' % (self.__class__.__name__, self.date)

    class Meta:
        managed = False
        db_table = 'cloud_top_twenty'
        unique_together = (('date', 'project_id'),)


class CloudPrivateCell(models.Model):
    """
    The projects that have an instances running for at least a day in
    our private cell
    """
    date = models.TextField(help_text="The date on which the values "
                                      "were calculated")
    project_id = models.CharField(max_length=32, help_text="The project ID")
    vcpus = models.IntegerField(help_text="The project VCPU count on the date")
    instances = models.IntegerField(
        help_text="The project instance count on the date")
    display_name = models.CharField(max_length=64,
                                    help_text="The project's formal name")
    organization = models.CharField(max_length=255,
                                    help_text="The organization the project "
                                              "belongs to")
    faculty = models.CharField(max_length=10,
                               default="Unknown",
                               help_text="The faculty the project belongs to")

    def __str__(self):
        return '%s: %s' % (self.__class__.__name__, self.date)

    class Meta:
        db_table = 'cloud_private_cell'
        unique_together = (('date', 'project_id'),)


class StorageTotalsByProduct(models.Model):
    date = models.TextField(primary_key=True, blank=False, null=False,
                            help_text="The date on which the values in "
                                      "the row were calculated"
                            )
    computational = models.DecimalField(blank=False,
                                        null=False,
                                        decimal_places=2,
                                        max_digits=15)
    market = models.DecimalField(blank=False,
                                 null=False,
                                 decimal_places=2,
                                 max_digits=15)
    vault = models.DecimalField(blank=False,
                                null=False,
                                decimal_places=2,
                                max_digits=15)

    def __str__(self):
        return '%s: %s' % (self.__class__.__name__, self.date)

    class Meta:
        managed = False
        abstract = True


class StorageAllocated(StorageTotalsByProduct):
    class Meta:
        managed = False
        db_table = 'storage_allocated'


class StorageUsed(StorageTotalsByProduct):
    class Meta:
        managed = False
        db_table = 'storage_used'


class StorageHeadroomUnused(StorageTotalsByProduct):
    class Meta:
        managed = False
        db_table = 'storage_headroom_unused'


class StorageCapacity(StorageTotalsByProduct):
    class Meta:
        managed = False
        db_table = 'storage_capacity'


class StorageHeadroomUnallocated(StorageTotalsByProduct):
    class Meta:
        managed = False
        db_table = 'storage_headroom_unallocated'

reports/views.py
import csv
import re
from datetime import date
from functools import wraps

import django
from dateutil.parser import parse
from dateutil.relativedelta import relativedelta
from django.apps import AppConfig
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone
from django.views import generic

from reports.graphite.capacity import fetch, GRAPHITE_JSON, GRAPHITE_CAPACITY
from .models import Report

LOGIN_URL = '/login/'
YEAR = 'year'


def _convert(name):
    """
    Converts the name parameter from CamelCase to snake case
    i.e.: CamelCase -> camel_case
    See:
    http://stackoverflow.com/questions/1175208/elegant-python-function-to-convert-camelcase-to-snake-case
    :param name: The camel case name to be converted
    :return: The input name as snake_case
    """
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


class BrowseView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    template_name = 'reports/reports.html'
    context_object_name = 'latest_report_list'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.selected_set = ''

    def get_queryset(self):
        """
        :return: All the published reports: excluding those published in
        the future.
        """
        reports = Report.objects.filter(pub_date__lte=timezone.now())
        self.selected_set = self.request.GET.get('set', '')
        if self.selected_set == 'cloud':
            reports = reports.filter(report_title__startswith='Cloud')
        elif self.selected_set == 'storage':
            reports = reports.filter(report_title__startswith='Storage')
        return reports.order_by('report_title')

    # we override this to add the selected set to the context
    # (is there a better way?)
    def get_context_data(self, **kwargs):
        result = super().get_context_data(**kwargs)
        result['set'] = self.selected_set
        return result


class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = LOGIN_URL
    model = Report
    template_name = 'reports/details.html'

    def get_queryset(self):
        """
        Excludes any reports that aren't published yet.
        """
        return Report.objects.filter(pub_date__lte=timezone.now())

    # we override this to add the debug flag to the context
    # (is there a better way?)
    def get_context_data(self, **kwargs):
        result = super().get_context_data(**kwargs)
        result['debug'] = settings.DEBUG
        result['set'] = self.request.GET.get('set', '')
        return result


def about(request):
    values = sorted(request.META.items())
    return render(request, 'reports/about.html',
                  {'details': values, 'debug': settings.DEBUG})


@login_required(login_url=LOGIN_URL)
def search(request):
    q = request.GET.get('q', None)
    if not q:
        errors = ['Please enter a search term!']
        return render(request, 'reports/search_form.html', {'errors': errors})
    reports = Report.objects.filter(report_title__icontains=q)
    if reports.count() > 0:
        return render(request, 'reports/search_results.html',
                      {'reports': reports, 'query': q})
    else:
        return render(request, 'reports/search_form.html', {'query': q})


def _get_start_date(duration):
    if duration == 'oneMonth':
        return date.today() - relativedelta(months=1)
    elif duration == 'threeMonths':
        return date.today() - relativedelta(months=3)
    elif duration == 'sixMonths':
        return date.today() - relativedelta(months=6)
    elif duration == 'all':
        return date(2012, 1, 1)
    else:
        # duration == YEAR:
        return date.today() - relativedelta(months=12)


# from
# http://stackoverflow.com/questions/22196422/django-login-required-on-ajax-call
def xmlhttp_login_required(view):
    @wraps(view)
    def wrapper(request, *args, **kwargs):
        if not request.user.is_authenticated():
            raise PermissionDenied
        return view(request, *args, **kwargs)
    return wrapper


@xmlhttp_login_required
def actual(request, path):
    """
    :return: A response with the model data presented as CSV. The data is
    filtered till today by date range
    """
    duration = request.GET.get('from', YEAR)
    # we default to a date range
    date_range_desired = (_get_start_date(duration), date.today())
    on = request.GET.get('on')
    if on:
        date_desired = parse(on).date()
        date_range_desired = (date_desired, date_desired)
    desired_model = request.GET.get('model', 'unknown')
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment;filename=%s.csv' % _convert(
        desired_model)
    writer = csv.writer(response)
    # if not specified 'unknown' will not be found and an error raised
    model = django.apps.apps.get_model('reports', desired_model)
    field_names = [f.name for f in model._meta.fields]
    writer.writerow(field_names)
    for instance in model.objects.filter(date__range=date_range_desired):
        writer.writerow([getattr(instance, f) for f in field_names])
    return response


@xmlhttp_login_required
def graphite(request, path):
    duration = request.GET.get('from', YEAR)
    capacity = request.GET.get('type', GRAPHITE_CAPACITY)
    desired_format = request.GET.get('format', GRAPHITE_JSON)
    graphite_response, content_type = fetch(capacity, desired_format, duration)
    response = HttpResponse(graphite_response, content_type)
    response['Content-Disposition'] = \
        'attachment; filename="capacity.%s"' % desired_format.lower()
    return response

reports/templates/reports/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block h1 %}About{% endblock %}

{% block content %}

    <p>This is a front end to a classic reporting database. As such, it
       offers a read only view of operational data.</p>
    <p>If you wish to gain access to the reports, you will need to
        <a href="{% url 'registration_register' %}">register</a>...
    </p><p>A manager will view your registration, and either approve or
           decline it.</p>
    <p>If approved, an email will be sent to the email address you provided
       with information on the further steps you will need to take to complete
       your account creation process.</p>

    {% if debug %}
        <table>
            <t>
                <th>Field</th>
                <th>Value</th>
            </t>
            {% for key, value in details %}
                <tr>
                    <td>{{ key }}</td>
                    <td>{{ value }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

{% endblock %}

reports/templates/reports/details.html
{% extends 'base.html' %}
{% block title %}Report Details{% endblock %}
{% block header_lines %}
    {% load static %}
    <link rel="stylesheet" type="text/css"
          href="//cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.5/nv.d3.css"/>
{% endblock %}

{% block h1 %}{{ report.report_title }}{% endblock %}
{% block content %}


    {% if error_message %}
        <section>
            <p><strong>{{ error_message }}</strong></p>
        </section>
    {% endif %}

    <section id="iReport">
        <div class="row">
            <div id="graph-buttons" class="btn-group pull-right">
                {# Buttons go here #}
            </div>
            <div id="iDateButtons" class="btn-group pull-right">
                {# Buttons go here #}
            </div>
        </div>

        <div id='chart' class='chart-wrapper'>
            <svg></svg>
        </div>

        <p>{{ report.description_html|safe }}</p>
        <p>The <a id="a_data" href="">data file</a> behind this graph</p>
    </section>

    {% if report.related %}
        <section>
            <div id="extra">
                <div id="extra_title"></div>
                {#  <p>{{ report.related.report_title }}</p> #}
                {# The line below should have no spaces in it #}
                {# At the moment a hacky work around to hide it if no graph #}
                {# is drawn on the uptime report #}
                {# @formatter:off #}
                <div class="chart-wrapper"><svg></svg></div>
                {# @formatter:on #}
                <div id="extra_link"></div>
            </div>
        </section>
    {% endif %}

    <section>
        <a href="/reports/?set={{ set }}">Back {% if not set %}to all
                                          reports {% endif %}...</a>
    </section>

    {# Following will be the latest v3 version of d3 #}
    {# If we want to control the version, use https://cdnjs.com/libraries/d3 #}
    <script src="//d3js.org/d3.v3.js"></script>
    {# From: https://cdnjs.com/libraries/nvd3 #}
    <script src="//cdnjs.cloudflare.com/ajax/libs/nvd3/1.8.5/nv.d3.js"></script>
    <script src="{% static "/reports/js/utils.js" %}"></script>
    <script src="{% static "/reports/js/charts/uptime_bullet.js" %}"></script>
    <script src="{% static "/reports/js/charts/uptime_history.js" %}"></script>
    <script src="{% static "/reports/js/spin.js" %}"></script>
    <script src="{% static '/reports/js/'|add:report.d3_file_name %}"></script>
    <script>
        report.d3.render();
    </script>

{% endblock %}

reports/templates/reports/reports.html
{%  extends 'base.html' %}
{%  block title %}Reports Available{% endblock %}
{%  block h1 %}Reports available{%  endblock %}
{%  block content %}
{% if latest_report_list %}
    <ul>
        {% for report in latest_report_list %}
            <li><a href="{% url 'reports:detail' report.id %}?set={{ set }}">{{ report.report_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No reports are available.</p>
{% endif %}
{% endblock %}

reports/templates/reports/search_form.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% block h1 %}Search{% endblock %}

{% block content %}

    {% if errors %}
        <ul>
            {% for error in errors %}
                <li>{{  error }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% if query %}
        <p>{{ query|capfirst }} not found...</p>
    {% endif %}

    <form action='' method="get">
        <input type="text" name="q"/>
        <input type="submit" value="Search"/>
    </form>

{% endblock %}

reports/templates/reports/search_results.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% block h1 %}Search{% endblock %}

{% block content %}

    <p>You searched for: <strong>{{ query }}</strong></p>

    {% if reports %}
        <p>Found {{ reports|length }} report{{ reports|pluralize }}</p>
        <ul>
            {% for report in reports %}
                <li><a href="/reports/{{ report.id }}">{{ report.report_title }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}