contact/urls.py
from django.conf.urls import url

from . import views

app_name = 'contact'
urlpatterns = [
    url(r'^$', views.contact, name='contact'),
]

reports/urls.py
from django.conf.urls import url

from . import views

app_name = 'reports'
urlpatterns = [
    url(r'^$', views.BrowseView.as_view(), name='reports'),
    url(r'^graphite/(.*)', views.graphite, name='graphite'),
    url(r'^actual/(.*)', views.actual, name='actual'),
    url(r'^about/$', views.about, name='about'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

reports_beta/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import index

admin.site.site_header = 'ResPlat Reporting: Administration'
admin.site.site_title = 'ResPlat Reporting'

urlpatterns = [
    url('^$', index, name='index'),
    url(r'^uom_admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^reports/', include('reports.urls')),
    url(r'^uom_admin/', admin.site.urls),
    url(r'^contact/', include('contact.urls')),
    url('^', include('django.contrib.auth.urls', namespace='auth')),
    url('^registration/', include('registration.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'reports/reset.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'reports/style.css' %}"/>
    <link rel="icon" type="image/png" sizes="32x32"
          href="{% static 'reports/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96"
          href="{% static 'reports/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16"
          href="{% static 'reports/favicon-16x16.png' %}">
    {% block header_lines %}{% endblock %}
</head>
<body>
<header id="iTop">
    <div id="iLogo">
        <a href="http://www.unimelb.edu.au/">
            <img src="//d2h9b02ioca40d.cloudfront.net/shared/assets/logo.svg"
                 alt="The University of Melbourne Logo">
        </a>
    </div>
    {% include 'nav.html' %}
    <div id="iHeading">
        <h1>{% block h1 %}{% endblock %}</h1>
    </div>
</header>

<section id="md_error" class="modalDialog">
    {# the error dialogue will cover the whole screen if an error is raised #}
    <div>
        <a id="md_close" href="#" title="Close" class="modalClose">X</a>
        <h2 id="md_title">There was a problem</h2>
        <p id="md_message"></p>
    </div>
</section>

<main>
    {# non repeated content is intended to go here #}
    {% block content %}{% endblock %}
    {# the push div is intended to reserve space for the fixed footer #}
    <div class="push"></div>
</main>

<footer>
    {# the footer has a fixed height #}
    {% block footer %}
        <p>Version: {{ SOURCE_REVISION }}</p>
    {% endblock %}
</footer>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}Reports{% endblock %}
{% block h1 %}Research Platforms Reporting{% endblock %}
{% block content %}
    <ul>
        <li>
            <a href="{% url 'reports:reports' %}?set=cloud">Cloud Reports</a>
        </li>
        <li>
            <a href="{% url 'reports:reports' %}?set=storage">Storage Reports</a>
        </li>
        <li>
            <a href="{% url 'reports:reports' %}">All Reports</a>
        </li>
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'admin:index' %}">Admin Console</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

templates/nav.html
<nav id="iNav">
    <ul>
        <li><a href="/">⌂ Home</a></li>
        <li><a href="{% url 'reports:search' %}">Search</a></li>
        <li><a href="{% url 'contact:contact' %}">Contact Us</a></li>
        <li><a href="{% url 'reports:about' %}">About</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'auth:logout' %}?next=/">Logout</a></li>
        {% else %}
            <li><a href="{% url 'auth:login' %}">Login</a></li>
        {% endif %}
    </ul>
</nav>